/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ClipYieldSponsorHubInterface extends Interface {
  getFunction(
    nameOrSignature: "kyc" | "sponsorClip" | "sponsorWithTerms" | "wmnt"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ClipSponsored" | "SponsoredCampaign"
  ): EventFragment;

  encodeFunctionData(functionFragment: "kyc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "sponsorClip",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sponsorWithTerms",
    values: [BytesLike, AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "wmnt", values?: undefined): string;

  decodeFunctionResult(functionFragment: "kyc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sponsorClip",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sponsorWithTerms",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wmnt", data: BytesLike): Result;
}

export namespace ClipSponsoredEvent {
  export type InputTuple = [
    clipHash: BytesLike,
    sponsor: AddressLike,
    vault: AddressLike,
    assets: BigNumberish
  ];
  export type OutputTuple = [
    clipHash: string,
    sponsor: string,
    vault: string,
    assets: bigint
  ];
  export interface OutputObject {
    clipHash: string;
    sponsor: string;
    vault: string;
    assets: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SponsoredCampaignEvent {
  export type InputTuple = [
    clipHash: BytesLike,
    sponsor: AddressLike,
    creator: AddressLike,
    vault: AddressLike,
    assets: BigNumberish,
    termsHash: BytesLike
  ];
  export type OutputTuple = [
    clipHash: string,
    sponsor: string,
    creator: string,
    vault: string,
    assets: bigint,
    termsHash: string
  ];
  export interface OutputObject {
    clipHash: string;
    sponsor: string;
    creator: string;
    vault: string;
    assets: bigint;
    termsHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ClipYieldSponsorHub extends BaseContract {
  connect(runner?: ContractRunner | null): ClipYieldSponsorHub;
  waitForDeployment(): Promise<this>;

  interface: ClipYieldSponsorHubInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  kyc: TypedContractMethod<[], [string], "view">;

  sponsorClip: TypedContractMethod<
    [clipHash: BytesLike, vault: AddressLike, assets: BigNumberish],
    [void],
    "nonpayable"
  >;

  sponsorWithTerms: TypedContractMethod<
    [
      clipHash: BytesLike,
      creator: AddressLike,
      vault: AddressLike,
      assets: BigNumberish,
      termsHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  wmnt: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "kyc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sponsorClip"
  ): TypedContractMethod<
    [clipHash: BytesLike, vault: AddressLike, assets: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sponsorWithTerms"
  ): TypedContractMethod<
    [
      clipHash: BytesLike,
      creator: AddressLike,
      vault: AddressLike,
      assets: BigNumberish,
      termsHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "wmnt"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ClipSponsored"
  ): TypedContractEvent<
    ClipSponsoredEvent.InputTuple,
    ClipSponsoredEvent.OutputTuple,
    ClipSponsoredEvent.OutputObject
  >;
  getEvent(
    key: "SponsoredCampaign"
  ): TypedContractEvent<
    SponsoredCampaignEvent.InputTuple,
    SponsoredCampaignEvent.OutputTuple,
    SponsoredCampaignEvent.OutputObject
  >;

  filters: {
    "ClipSponsored(bytes32,address,address,uint256)": TypedContractEvent<
      ClipSponsoredEvent.InputTuple,
      ClipSponsoredEvent.OutputTuple,
      ClipSponsoredEvent.OutputObject
    >;
    ClipSponsored: TypedContractEvent<
      ClipSponsoredEvent.InputTuple,
      ClipSponsoredEvent.OutputTuple,
      ClipSponsoredEvent.OutputObject
    >;

    "SponsoredCampaign(bytes32,address,address,address,uint256,bytes32)": TypedContractEvent<
      SponsoredCampaignEvent.InputTuple,
      SponsoredCampaignEvent.OutputTuple,
      SponsoredCampaignEvent.OutputObject
    >;
    SponsoredCampaign: TypedContractEvent<
      SponsoredCampaignEvent.InputTuple,
      SponsoredCampaignEvent.OutputTuple,
      SponsoredCampaignEvent.OutputObject
    >;
  };
}
