/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ClipYieldSponsorHub } from "./ClipYieldSponsorHub";
export type { IClipYieldBoostVault } from "./IClipYieldBoostVault";
export type { IKycRegistry } from "./IKycRegistry";
