/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as clipYieldBoostPassSol from "./ClipYieldBoostPass.sol";
export type { clipYieldBoostPassSol };
import type * as clipYieldBoostVaultSol from "./ClipYieldBoostVault.sol";
export type { clipYieldBoostVaultSol };
import type * as clipYieldSponsorHubSol from "./ClipYieldSponsorHub.sol";
export type { clipYieldSponsorHubSol };
import type * as clipYieldVaultSol from "./ClipYieldVault.sol";
export type { clipYieldVaultSol };
export type { ClipYieldBoostVaultFactory } from "./ClipYieldBoostVaultFactory";
export type { KycRegistry } from "./KycRegistry";
