/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IKycRegistry,
  IKycRegistryInterface,
} from "../../../../contracts/realfi/ClipYieldBoostPass.sol/IKycRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "isVerified",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IKycRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IKycRegistryInterface {
    return new Interface(_abi) as IKycRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IKycRegistry {
    return new Contract(address, _abi, runner) as unknown as IKycRegistry;
  }
}
