/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IClipYieldBoostVault,
  IClipYieldBoostVaultInterface,
} from "../../../../contracts/realfi/ClipYieldSponsorHub.sol/IClipYieldBoostVault";

const _abi = [
  {
    inputs: [],
    name: "asset",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "assets",
        type: "uint256",
      },
    ],
    name: "donateYield",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IClipYieldBoostVault__factory {
  static readonly abi = _abi;
  static createInterface(): IClipYieldBoostVaultInterface {
    return new Interface(_abi) as IClipYieldBoostVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IClipYieldBoostVault {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IClipYieldBoostVault;
  }
}
