/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ClipYieldBoostVault__factory } from "./ClipYieldBoostVault__factory";
export { IKycRegistry__factory } from "./IKycRegistry__factory";
