/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ClipYieldVault__factory } from "./ClipYieldVault__factory";
export { IKycRegistry__factory } from "./IKycRegistry__factory";
