/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ClipYieldBoostVault } from "./ClipYieldBoostVault";
export type { IKycRegistry } from "./IKycRegistry";
